// This is automatically generated by bootstrap-js-compiler.ss
// Please don't hand-edit this file.
(function(_that) {var _SHARED = {};
var arity_colon_fixed = function (n) { plt.types.Struct.call(this, "make-arity:fixed", [n]);this.n = n; };
arity_colon_fixed.prototype = new plt.types.Struct();

var make_dash_arity_colon_fixed = function (id0) { return new arity_colon_fixed(id0); };
var arity_colon_fixed_dash_n = function(obj) {
     if (arity_colon_fixed_question_ (obj)) {
        return obj.n;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('arity:fixed-n: not a arity:fixed: ~s', [obj]));
     }
};

var set_dash_arity_colon_fixed_dash_n_bang_ = function(obj,newVal) {
	 if (arity_colon_fixed_question_ (obj)) {
		obj.n = newVal;
           obj._fields[0] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_arity_colon_fixed_dash_n_bang_: not a arity:fixed: ~s', [obj]));
     }
};

var arity_colon_fixed_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof arity_colon_fixed; };

var arity_colon_variable = function (min,max) { plt.types.Struct.call(this, "make-arity:variable", [min,max]);this.min = min;
this.max = max; };
arity_colon_variable.prototype = new plt.types.Struct();

var make_dash_arity_colon_variable = function (id0,id1) { return new arity_colon_variable(id0,id1); };
var arity_colon_variable_dash_min = function(obj) {
     if (arity_colon_variable_question_ (obj)) {
        return obj.min;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('arity:variable-min: not a arity:variable: ~s', [obj]));
     }
};

var arity_colon_variable_dash_max = function(obj) {
     if (arity_colon_variable_question_ (obj)) {
        return obj.max;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('arity:variable-max: not a arity:variable: ~s', [obj]));
     }
};

var set_dash_arity_colon_variable_dash_min_bang_ = function(obj,newVal) {
	 if (arity_colon_variable_question_ (obj)) {
		obj.min = newVal;
           obj._fields[0] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_arity_colon_variable_dash_min_bang_: not a arity:variable: ~s', [obj]));
     }
};

var set_dash_arity_colon_variable_dash_max_bang_ = function(obj,newVal) {
	 if (arity_colon_variable_question_ (obj)) {
		obj.max = newVal;
           obj._fields[1] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_arity_colon_variable_dash_max_bang_: not a arity:variable: ~s', [obj]));
     }
};

var arity_colon_variable_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof arity_colon_variable; };

var arity_colon_mixed = function (arities) { plt.types.Struct.call(this, "make-arity:mixed", [arities]);this.arities = arities; };
arity_colon_mixed.prototype = new plt.types.Struct();

var make_dash_arity_colon_mixed = function (id0) { return new arity_colon_mixed(id0); };
var arity_colon_mixed_dash_arities = function(obj) {
     if (arity_colon_mixed_question_ (obj)) {
        return obj.arities;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('arity:mixed-arities: not a arity:mixed: ~s', [obj]));
     }
};

var set_dash_arity_colon_mixed_dash_arities_bang_ = function(obj,newVal) {
	 if (arity_colon_mixed_question_ (obj)) {
		obj.arities = newVal;
           obj._fields[0] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_arity_colon_mixed_dash_arities_bang_: not a arity:mixed: ~s', [obj]));
     }
};

var arity_colon_mixed_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof arity_colon_mixed; };

var arity_question_ = function(x) { return (arity_colon_fixed_question_(x)||arity_colon_variable_question_(x)||arity_colon_mixed_question_(x)); };
var arity_dash__greaterthan_sexp = function(an_dash_arity) { return (arity_colon_fixed_question_(an_dash_arity) ?
 plt.Kernel.list([(plt.types.Symbol.makeInstance("arity:fixed")),arity_colon_fixed_dash_n(an_dash_arity)]) :
 (arity_colon_variable_question_(an_dash_arity) ?
 plt.Kernel.list([(plt.types.Symbol.makeInstance("arity:variable")),arity_colon_variable_dash_min(an_dash_arity),arity_colon_variable_dash_max(an_dash_arity)]) :
 (arity_colon_mixed_question_(an_dash_arity) ?
 plt.Kernel.list([(plt.types.Symbol.makeInstance("arity:mixed")),plt.Kernel.map((plt.types.liftToplevelToFunctionValue(arity_dash__greaterthan_sexp,(plt.types.String.makeInstance("arity->sexp")),1,(plt.types.Rational.makeInstance(1, 1)))), [arity_colon_mixed_dash_arities(an_dash_arity)])]) :
 plt.Kernel.error((plt.types.Symbol.makeInstance("cond")),_SHARED[4])))); };
var sexp_dash__greaterthan_arity = function(an_dash_sexp) { return (plt.Kernel.list_question_(an_dash_sexp) ?
 ((plt.Kernel.symbol_equal__question_(plt.Kernel.first(an_dash_sexp),(plt.types.Symbol.makeInstance("arity:fixed?")))&&plt.Kernel._equal_(_SHARED[5],plt.Kernel.length(an_dash_sexp), [])&&plt.Kernel.number_question_(plt.Kernel.second(an_dash_sexp))) ?
 make_dash_arity_colon_fixed(plt.Kernel.second(an_dash_sexp)) :
 ((plt.Kernel.symbol_equal__question_(plt.Kernel.first(an_dash_sexp),(plt.types.Symbol.makeInstance("arity:variable?")))&&plt.Kernel._equal_(_SHARED[6],plt.Kernel.length(an_dash_sexp), [])&&(plt.Kernel.number_question_(plt.Kernel.second(an_dash_sexp))||plt.Kernel.false_question_(plt.Kernel.second(an_dash_sexp)))&&(plt.Kernel.number_question_(plt.Kernel.third(an_dash_sexp))||plt.Kernel.false_question_(plt.Kernel.third(an_dash_sexp)))) ?
 make_dash_arity_colon_variable(plt.Kernel.second(an_dash_sexp),plt.Kernel.third(an_dash_sexp)) :
 ((plt.Kernel.symbol_equal__question_(plt.Kernel.first(an_dash_sexp),(plt.types.Symbol.makeInstance("arity:mixed?")))&&plt.Kernel.list([plt.Kernel.second(an_dash_sexp)])) ?
 ((function() { 

var inner_dash_arities; 
(function (toplevel_dash_expression_dash_show7) { 
inner_dash_arities = plt.Kernel.map((plt.types.liftToplevelToFunctionValue(sexp_dash__greaterthan_arity,(plt.types.String.makeInstance("sexp->arity")),1,(plt.types.Rational.makeInstance(1, 1)))), [plt.Kernel.second(an_dash_sexp)]); })(plt.Kernel.identity)
return (plt.Kernel.andmap(((function() {
   var _result_ = (function(args8) {
var x = args8[0];  return (arity_colon_fixed_question_(x)||arity_colon_variable_question_(x)); });_result_._eqHashCode = plt.types.makeEqHashCode();_result_.toWrittenString = function (cache) { return '<function:lambda>'; };_result_.isEqual = function(other, cache) { return this === other; };_result_.procedureArity = (plt.types.Rational.makeInstance(1, 1));_result_.toDisplayedString = _result_.toWrittenString;return _result_;  })()), [inner_dash_arities]) ?
 make_dash_arity_colon_mixed(inner_dash_arities) :
 (plt.types.Logic.TRUE ?
 plt.Kernel.error((plt.types.Symbol.makeInstance("sexp->arity")),plt.Kernel.format(_SHARED[9], [an_dash_sexp])) :
 plt.Kernel.error((plt.types.Symbol.makeInstance("cond")),_SHARED[4])));
              })()) :
 plt.Kernel.error((plt.types.Symbol.makeInstance("cond")),_SHARED[4])))) :
 (plt.types.Logic.TRUE ?
 plt.Kernel.error((plt.types.Symbol.makeInstance("sexp->arity")),plt.Kernel.format(_SHARED[9], [an_dash_sexp])) :
 plt.Kernel.error((plt.types.Symbol.makeInstance("cond")),_SHARED[4]))); };_SHARED[6] = (plt.types.Rational.makeInstance(3, 1));
_SHARED[4] = (plt.types.String.makeInstance("cond: fell out of cond"));
_SHARED[9] = (plt.types.String.makeInstance("Does not look like an arity structure: ~s"));
_SHARED[5] = (plt.types.Rational.makeInstance(2, 1));

(function() { 
  ((function (toplevel_dash_expression_dash_show0) { 





 })  )(arguments[0] || plt.Kernel.identity);
_that["arity_colon_mixed"] = arity_colon_mixed;
_that["make_dash_arity_colon_mixed"] = make_dash_arity_colon_mixed;
_that["arity_colon_mixed_question_"] = arity_colon_mixed_question_;
_that["arity_colon_mixed_dash_arities"] = arity_colon_mixed_dash_arities;
_that["set_dash_arity_colon_mixed_dash_arities_bang_"] = set_dash_arity_colon_mixed_dash_arities_bang_;
_that["arity_colon_variable"] = arity_colon_variable;
_that["make_dash_arity_colon_variable"] = make_dash_arity_colon_variable;
_that["arity_colon_variable_question_"] = arity_colon_variable_question_;
_that["arity_colon_variable_dash_min"] = arity_colon_variable_dash_min;
_that["arity_colon_variable_dash_max"] = arity_colon_variable_dash_max;
_that["set_dash_arity_colon_variable_dash_min_bang_"] = set_dash_arity_colon_variable_dash_min_bang_;
_that["set_dash_arity_colon_variable_dash_max_bang_"] = set_dash_arity_colon_variable_dash_max_bang_;
_that["arity_question_"] = arity_question_;
_that["arity_colon_fixed"] = arity_colon_fixed;
_that["make_dash_arity_colon_fixed"] = make_dash_arity_colon_fixed;
_that["arity_colon_fixed_question_"] = arity_colon_fixed_question_;
_that["arity_colon_fixed_dash_n"] = arity_colon_fixed_dash_n;
_that["set_dash_arity_colon_fixed_dash_n_bang_"] = set_dash_arity_colon_fixed_dash_n_bang_;
})();})(this);
